### ISSUE TITLE
feat:/ui Разработать навигационный список в блоке header

### ISSUE THREAD

**Issue by Saitnbone** [Saitnbone/shop.co-project__frontend#12]
# Задача 

Необходимо разработать навигационный список для блока header.
Работать следует в widgets/header/ui/components

Подключить готовый результат к Layout.tsx

**Изображение навигационного списка.**

![Image](https://github.com/user-attachments/assets/574c4a0a-40f4-4fa5-87d8-2e82dea0b374)

## Требования кода

ОБЯЗАТЕЛЬНО!

- Создайте ветку.
- перед началом работы в ветке  извлеките изменения из ветки 'develop' с помощью команды git pull origin development;
- работайте в ветке;
- не используйте тип any.

## Правила формирования коммитов:

Во время работы не делайте больших коммитов, создавайте небольшие атомарные коммиты с фиксированным функционалом, описывайте, что вы делали в комментарии к коммиту. Например, мы добавили новый компонент или исправили одну конкретную ошибку. Не делайте коммиты типа «Исправленные ошибки», «Добавлены компоненты», «Рефакторинг кода». Все это нужно разбить на небольшие коммиты с описанием, что именно было сделано.
При именовании коммитов используйте следующие условные префиксы:

``feat:`` - новый функционал;
``fix:`` - исправление багов
``ref:`` - рефакторинг уже существующего кода;
``chore:`` -изменения, не связанные с производственным кодом, например тесты, документация, настройки сборки.

**Пример:** fix: fixed a bug with an incorrect date.

![Image](https://github.com/user-attachments/assets/574c4a0a-40f4-4fa5-87d8-2e82dea0b374)

**Comment by E-Okishev** [comment]
https://github.com/Saitnbone/shop.co-project__frontend/pull/13
