### ISSUE TITLE
feat:/ui Сделать поисковый инпут в блоке header

### ISSUE THREAD

**Issue by Saitnbone** [Saitnbone/shop.co-project__frontend#14]
# Задача 

Необходимо разработать поисковый инпут в блоке header. 
Разместить в слое бизнес-логики features/search-input

**Изображение**

![Image](https://github.com/user-attachments/assets/1b5bbf9e-75a0-4bff-9cfb-222353c44e2d)

## Требования кода

ОБЯЗАТЕЛЬНО!

- Создайте ветку.
- перед началом работы в ветке  извлеките изменения из ветки 'develop' с помощью команды git pull origin development;
- работайте в ветке;
- не используйте тип any.

## Правила формирования коммитов:

Во время работы не делайте больших коммитов, создавайте небольшие атомарные коммиты с фиксированным функционалом, описывайте, что вы делали в комментарии к коммиту. Например, мы добавили новый компонент или исправили одну конкретную ошибку. Не делайте коммиты типа «Исправленные ошибки», «Добавлены компоненты», «Рефакторинг кода». Все это нужно разбить на небольшие коммиты с описанием, что именно было сделано.
При именовании коммитов используйте следующие условные префиксы:

``feat:`` - новый функционал;
``fix:`` - исправление багов
``ref:`` - рефакторинг уже существующего кода;
``chore:`` -изменения, не связанные с производственным кодом, например тесты, документация, настройки сборки.

**Пример:** fix: fixed a bug with an incorrect date.

**Comment by Saitnbone** [comment]
Нет пулл реквеста

**Comment by E-Okishev** [comment]
https://github.com/Saitnbone/shop.co-project__frontend/pull/30
