### ISSUE TITLE
feat:/ui Разработать блоки со списками в footer

### ISSUE THREAD

**Issue by Saitnbone** [Saitnbone/shop.co-project__frontend#20]
# Задача 
Необходимо подготовить списки в footer 
Работать в widgets/footer

*Изображение*
![Image](https://github.com/user-attachments/assets/84164367-b843-467c-91a7-71fac380f0c8)

## Требования кода

ОБЯЗАТЕЛЬНО!

- Создайте ветку.
- перед началом работы в ветке  извлеките изменения из ветки 'develop' с помощью команды git pull origin development;
- работайте в ветке;
- не используйте тип any.

## Правила формирования коммитов:

Во время работы не делайте больших коммитов, создавайте небольшие атомарные коммиты с фиксированным функционалом, описывайте, что вы делали в комментарии к коммиту. Например, мы добавили новый компонент или исправили одну конкретную ошибку. Не делайте коммиты типа «Исправленные ошибки», «Добавлены компоненты», «Рефакторинг кода». Все это нужно разбить на небольшие коммиты с описанием, что именно было сделано.
При именовании коммитов используйте следующие условные префиксы:

``feat:`` - новый функционал;
``fix:`` - исправление багов
``ref:`` - рефакторинг уже существующего кода;
``chore:`` -изменения, не связанные с производственным кодом, например тесты, документация, настройки сборки.

**Пример:** fix: fixed a bug with an incorrect date.

**Comment by annakarpova9** [comment]
В этой же задача сделана задача 25. [PR](https://github.com/Saitnbone/shop.co-project__frontend/pull/28)
