### ISSUE TITLE
Feat:/ui Реализовать слайдер с логотипами

### ISSUE THREAD

**Issue by E-Okishev** [Saitnbone/shop.co-project__frontend#40]
### Перед началом работы
- git pull
- git fetch origin
- git checkout feat/-task_40

Необходимо сверстать компонент
![Image](https://github.com/user-attachments/assets/b54ef1a7-dd7d-43fa-84ec-4c2a5b52e33e)

Сверстать сладйер, слайдер должен автоматически листаться и быть зацикленным (те бесконечным). При адаптиве не надо делать в 2 строчки логотипы. Они также в одну листаться должны

## Требования кода
ОБЯЗАТЕЛЬНО!

- Создайте ветку;
- перед началом работы в ветке извлеките изменения из ветки 'develop' с помощью команды git pull origin development;
- работайте в ветке;
- не используйте тип any.

## Правила формирования коммитов:
Во время работы не делайте больших коммитов, создавайте небольшие атомарные коммиты с фиксированным функционалом, описывайте, что вы делали в комментарии к коммиту. Например, мы добавили новый компонент или исправили одну конкретную ошибку. Не делайте коммиты типа «Исправленные ошибки», «Добавлены компоненты», «Рефакторинг кода». Все это нужно разбить на небольшие коммиты с описанием, что именно было сделано.
При именовании коммитов используйте следующие условные префиксы:

`feat`: - новый функционал;
`fix`: - исправление багов
`ref`: - рефакторинг уже существующего кода;
`chore`: -изменения, не связанные с производственным кодом, например тесты, документация, настройки сборки.

**Пример:** fix: fixed a bug with an incorrect date.

**Comment by annakarpova9** [comment]
[PR](https://github.com/Saitnbone/shop.co-project__frontend/pull/48)
